### ISSUE TITLE
Create a treeview-style list view for emails

### ISSUE THREAD

**Issue by Humbedooh** [quenda/ponymail#21]
A treeview where threads are listed as trees but not expanded into bodies would be awful nice. This would supplement the threaded/flat views.

**Comment by ulises** [comment]
each node in the tree is the subject and is expanded on click?

**Comment by Humbedooh** [comment]
Exactly! like the old pipermail/mod_mbox way of just displaying the subject lines as a treeview and clicking expands each email individually. I have a fix in the pipeline right now.

**Comment by Humbedooh** [comment]
Should we add "bars/lines" to this to show how the tree is structured?

**Comment by ulises** [comment]
you mean the edges between the nodes in the trees? I'd think so.

**Comment by Humbedooh** [comment]
Pondering on whether this can be closed as fixed now..? WDYT?

**Comment by ulises** [comment]
:+1:

**Comment by Humbedooh** [comment]
Alright, closing as fixed then. Any additional tweaks to the view shouldn't be hindered by that.
