### ISSUE TITLE
Request for spefic use case documentation

### ISSUE THREAD

**Issue by ilgrosso** [quenda/ponymail#24]
I would like to setup PonyMail for my company infrastructure.
We have several mailing lists managed by Mailman 2.1 on Ubuntu 14.0.4 LTS; some of them have private archives, other are public.

Would it be possible to provide more detailed setup instructions for a use case as the one above?
I have attempted following the [Ubuntu setup instructions](https://github.com/quenda/ponymail/blob/master/docs/INSTALL.ubuntu.md) and then the [general instructions](https://github.com/quenda/ponymail/blob/master/docs/INSTALLING.md) but could not figure out how to:
  1. configure Mailman 2.1 (examples for Mailman 3 are provided)
  1. index existing Mailman (public and private) archives

Thanks in advance, PonyMail rocks!

**Comment by Humbedooh** [comment]
Hi,
We use Mailman 2.1 for ponymail.info (the pony mail mailing list), so it's definitely possible.
for 1) you would normally subscribe a local alias to public lists and one to private lists, see https://github.com/quenda/ponymail/blob/master/docs/INSTALLING.md#setting-up-the-archiver for that. It's important to note that you'll need one alias for public lists and one for private lists.

As for 2), please see docs/IMPORTING.md. As you have public and private archives, you'll need to run the import-mbox script separately for the public and private (adding --private for private imports).
What sort of archive are you importing from?

And don't worry, I'll be updating the docs as we go along :)

There is also step 3, which is using AAA (Authentication, Authorization and Access) to make private archives visible to those that should have access, but we'll cross that bridge soon enough. It's a bit more complex.

**Comment by ilgrosso** [comment]
Thanks for your helpful hints, I'll have some time to allocate to this at beginning of next week.

> What sort of archive are you importing from?

pipermail, so it should be already covered by

Thanks for support and wish you happy 2016!

**Comment by Humbedooh** [comment]
Yeah, luckily pipermail is very easy to import from nowadays. It has some quirks, so you'll need to latest version of master to import it correctly (there are some email address rewrites involved here)

**Comment by ilgrosso** [comment]
Quick update: importing via pipermail seems to work fine; got long output ending with

```
All done! 3765 records inserted/updated after 0 seconds. 0 records were bad and ignored
```

However, right after importing (but still without configuring the archiver yet), while accessing the ponymail site I receive a couple of errors:

 1. `404'ed: /api/pminfo.lua`
 1. `404'ed: /api/preferences.lua?detailed=true`

Any hint?
Thanks!

**Comment by Humbedooh** [comment]
import-mbox and archiver both use the same ID generator, which generates a unique ID per email - that is to say, running it twice on the same email or mbox file will generate the same ID, so if you run import-mbox every 5 minutes or whatever, it'll just update what's already there, and not create duplicates (IOW, it's totally fine to do that, just remember to use --private where needed).

As for the 404, Pony Mail expects to be at the root of a (sub)domain - this is due to some non-javascript fallbacks that exist for older web clients (or lynx). Thus, http://foo.tld/api/[...].lua will work, but http://foo.tld/ponymail/[...].lua won't work currently because of this design choice.

I'll look into writing a workaround shortly, which will imply that you can't use the site unless you have JavaScript enabled. This will be an optional feature in config.js

**Comment by Humbedooh** [comment]
580f1e82a018c3cc32e50f6d26e3866a39078b29 should address this - go to your config.js, and inside the `pm_config` hash, add: `URLBase: '/yoursubdir'` to it and it should work.

**Comment by Humbedooh** [comment]
FWIW, I have a few lists that are imported "live" from pipermail, such as the bitcoin ML. I just have import-mbox running on a cron timer, and it works well. Another option is to subscribe a new mail address to the lists, and have that mail address feed to the archiver, which is what you'd normally do in many cases.

**Comment by Humbedooh** [comment]
I'll also suggest maybe joining #ponymail on Freenode for some of the more menial debugging, as it's probably a better way of communicating about that.

**Comment by ilgrosso** [comment]
Yep, thanks, I'm closing this issue and switching to IRC.
