### ISSUE TITLE
Mailman, pipermail and HTML attachments

### ISSUE THREAD

**Issue by ilgrosso** [quenda/ponymail#26]
We unfortunately have someone in our MLs sending e-mails in HTML only: as a result, pipermail will display a blank e-mail saying "An HTML attachment was scrubbed...", with link to such HTML attachment.

This also works in PonyMail, but I was wondering if:
 1. PonyMail scans such attachment when importing from pipermail
 1. Is it possible to make PonyMail display such attachment inline (only when no text version is available)

**Comment by Humbedooh** [comment]
I wonder if this should be an option turned off by default, but available in the preferences?
That is, by default, it should say "this message appears to be html only, would you like to show it bla bla bla?" with an option in preferences to just open up inline by default if nothing else is in the mail.

**Comment by ilgrosso** [comment]
+1

But what about indexing? Does PonyMail import tool scans such HTML attachments?

**Comment by Humbedooh** [comment]
fair point - no it does not scan them for content at present, it assumes they are attachments and not the main message. I'm not sure how much....rendering of the page would have to take place for this to be a meaningful thing to do.

**Comment by ilgrosso** [comment]
> rendering of the page would have to take place for this to be a meaningful thing to do

well, not completely: I'd say most of the text can be read anyway by mean of something like as [html2text](http://www.aaronsw.com/2002/html2text/)

**Comment by Humbedooh** [comment]
I've added a --html2text arg for the archiver/importer, and after a long struggle, it seems to be working now. Please take it for a spin, but do beware that the emails affected will duplicate themselves, as their ID in Pony Mail will update because of this.

**Comment by ilgrosso** [comment]
It works now, with the `--html2text` option for `import-mbox.py`and bypassing pipermail.

Thanks!
