### ISSUE TITLE
Privacy issue: thread.html view - first email address in the list, the sender email is not obfuscated

### ISSUE THREAD

**Issue by shazron** [quenda/ponymail#55]
Email addresses are generally obfuscated, except for the first email in the thread.

## Expected:
The first "from:" email address in a thread should be obfuscated, like the rest of the emails in a thread.

## Actual:
The first "from:" email address in a thread is not obfuscated, unlike the rest of the emails in a thread.

## Steps to repro:

1. In  the main view, expand a thread.
2. Click on the "Permalink" button on any email in the thread
3. Note that in the new Thread view, the first email's "From:" field is not obfuscated

## Example deployment to see the bug in action:
http://ponymail.info/thread.html/Z3uzyw5jakfvdqq

**Comment by Humbedooh** [comment]
This should be fixed now. The anonymizing feature that the stats generator (the script that pulls down monthly views) had was not being applied in the thread display script, but it is there now and looks to be working :)
